name: Build Android APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Flutter Doctor
      run: flutter doctor -v
        
    - name: Get dependencies
      run: |
        flutter clean
        flutter pub get
      
    - name: Create Firebase config files
      run: |
        mkdir -p android/app
        echo '{"project_info":{"project_number":"123456789","project_id":"food-recognition-app-ci","storage_bucket":"food-recognition-app-ci.appspot.com"},"client":[{"client_info":{"mobilesdk_app_id":"1:123456789:android:abcdef123456","android_client_info":{"package_name":"com.foodrecognition.food_recognition_app"}},"oauth_client":[],"api_key":[{"current_key":"fake-api-key-for-ci-build"}],"services":{"appinvite_service":{"other_platform_oauth_client":[]}}}],"configuration_version":"1"}' > android/app/google-services.json
        
        mkdir -p ios/Runner
        cat > ios/Runner/GoogleService-Info.plist << "EOF"
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
        	<key>CLIENT_ID</key>
        	<string>123456789-fake.apps.googleusercontent.com</string>
        	<key>REVERSED_CLIENT_ID</key>
        	<string>com.googleusercontent.apps.123456789-fake</string>
        	<key>API_KEY</key>
        	<string>fake-api-key-for-ci-build</string>
        	<key>GCM_SENDER_ID</key>
        	<string>123456789</string>
        	<key>PLIST_VERSION</key>
        	<string>1</string>
        	<key>BUNDLE_ID</key>
        	<string>com.foodrecognition.food-recognition-app</string>
        	<key>PROJECT_ID</key>
        	<string>food-recognition-app-ci</string>
        	<key>STORAGE_BUCKET</key>
        	<string>food-recognition-app-ci.appspot.com</string>
        	<key>IS_ADS_ENABLED</key>
        	<false/>
        	<key>IS_ANALYTICS_ENABLED</key>
        	<false/>
        	<key>IS_APPINVITE_ENABLED</key>
        	<true/>
        	<key>IS_GCM_ENABLED</key>
        	<true/>
        	<key>IS_SIGNIN_ENABLED</key>
        	<true/>
        	<key>GOOGLE_APP_ID</key>
        	<string>1:123456789:ios:abcdef123456</string>
        </dict>
        </plist>
        EOF

    - name: Build APK (Debug)
      run: |
        echo "Building debug APK..."
        flutter build apk --debug --no-shrink --verbose
        if [ -d "build/app/outputs/flutter-apk" ]; then
          ls -la build/app/outputs/flutter-apk/
        else
          echo "Debug APK build failed - no output directory"
          exit 1
        fi
      
    - name: Build APK (Release) 
      run: |
        echo "Building release APK..."
        flutter build apk --release --no-shrink --verbose
        if [ -d "build/app/outputs/flutter-apk" ]; then
          ls -la build/app/outputs/flutter-apk/
        else
          echo "Release APK build failed - no output directory"
          exit 1
        fi
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-*-debug.apk
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-*-release.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0-${{ github.run_number }}
        name: Food Recognition App v1.0.0-${{ github.run_number }}
        body: |
          ## What's New
          - AI-powered food recognition
          - Recipe suggestions based on detected ingredients
          - Premium subscription features
          
          ## Installation
          1. Download the APK file below
          2. Enable "Install from unknown sources" in Android settings
          3. Install the APK on your device
          
        files: |
          build/app/outputs/flutter-apk/app-*-release.apk
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
